# -*- coding: utf-8 -*-
"""Board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zh6wh58LcRDpFP7ycUIVvsZ32EBkSPc9
"""

board = [["-" for a in range (3)] for b in range (3)]
for row in board:
  print(row)